### PR TITLE
On error only fetch a new JWT, let Phoenix do the reconnection

### LINKED ISSUE #182: Set upper limit to consecutive reconnections
In a situation where the websocket server connects and then immediately closes the connection for some reason, the Lasagna client will immediately try to reconnect, causing an endless loop of retries.

p1641480245001100-slack-C010KDAPG49

### PR DESCRIPTION
**Pull request by jsnajdr**
Fixes #182. When the websocket fires an `error` event, we don't reconnect, but only fetch the new JWT token if it's expired. The reconnection will be handled by Phoenix internally. If the JWT is expired, a few reconnections will still fail until the REST response with the new token arrives and the token is stored in a `jwt` variable.

The `params` object that contains the `jwt` field is being modified to a callback, so that the latest value of `jwt` is always used.

I believe that the infinite loop was caused by both Phoenix and Lasagna trying to furiously reconnect and fetch the token on each `error` event.

**How to test:**
That will be a long journey. Update the `lasagna` package in the P2 project, rebuild it, deploy to wpcom and then test that a P2 page still has working Lasagna client and that it reconnects on error.

### CODE REVIEW

**Comment by mirka** [comment]
This is how I'm testing:

1. Sandbox `public-api` and an arbitrary P2.
2. Alter the auth endpoint to make the JWT expire in 60 seconds.
3. Open the P2 in the browser and monitor the websocket messages.

The problem is that I cannot reproduce the infinite loop, even before the Lasagna client patch. The JWT expires, and the client eventually rejoins the channel successfully. Is there a more reliable way to reproduce the infinite loop?

**Comment by jsnajdr** [comment]
> The problem is that I cannot reproduce the infinite loop, even before the Lasagna client patch.

I cannot reproduce it either, we only know from server logs that it's the `/wpcom/v2/lasagna/jwt/sign` endpoint that gets a flood of requests, that their origin are P2 pages, and that the `jwt_type` of all of these requests is `socket`.

> The JWT expires, and the client eventually rejoins the channel successfully

To clarify, the errors we are seeing are never about a channel JWT expiring and the client requesting a `jwt_type: 'channel'` token and then rejoining. It's always that the `socket` token is requested, and that happens after the previous websocket connection is broken and needs to be re-established.

At this moment I think it's unlikely that we'll be able to reproduce the infinite loop locally and then apply a patch and confirm that it's gone. It's more like verifying that the change looks reasonable and that when tested, it doesn't break anything even more.

**Review by mirka — APPROVED** [review]
Ok, then it's working as expected 👍 Code changes look good as well.

**Review by tyxla — APPROVED** [review]
Code makes sense. 👍 

Approving since testing on the related patch with WP.com worked well ✅

**Pull request merged**
